M48
; DRILL file {KiCad 7.0.10} date Thursday, January 25, 2024 at 08:05:27 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-25T20:05:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.396Y-4.617
X5.405Y-3.402
X7.71Y-4.617
X7.721Y-3.4
M30
